---
# This task is looped on from tasks/main.yml and the variable
# wireguard_interface represents the wireguard interface being configured
# (e.g. wg0, wg1).

- name: expand the configuration
  set_fact:
    wireguard_conf: >
      {{
        wireguard[wireguard_interface] |
        auto_assign_ips                |
        remove_self
      }}

- name: create config file
  template:
    src: templates/etc/wireguard/wireguard_interface.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: 0600

- name: enable wg-quick
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes

- name: configure unbound records
  include_tasks: configure_unbound_records.yml
  when: wireguard_conf.unbound_records|default(false)

- name: create mobile config
  include_tasks: configure_mobile.yml
  with_items: "{{ wireguard_conf.peers.keys()|list|sort }}"
  loop_control:
    loop_var: peername
  when: >
    wireguard_generate_mobile and
    wireguard[wireguard_interface].peers[peername].mobile|default(False)
