---

- name: "Create wireguard mobile directory if necessary"
  file:
    path: "{{ wireguard_mobile_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: "collect the private key of {{ peername }}"
  set_fact:
    wireguard_mobile_privkey: >
      {{
        wireguard[wireguard_interface].peers[peername].privkey |
        default('<your private key here>')
      }}

- name: "adjusting {{ peername }} config variables"
  set_fact:
    wireguard_mobile_conf: >
      {{
        wireguard[wireguard_interface]                 |
        combine({'privkey': wireguard_mobile_privkey}) |
        auto_assign_ips                                |
        remove_self
      }}
    wireguard_mobile_conf_clean: {}

- name: "removing the fields that are irrelevant for mobile devices"
  set_fact:
    wireguard_mobile_conf_clean: >
      {{
        wireguard_mobile_conf          |
        combine({item.key: item.value})
      }}
  with_dict: "{{ wireguard_mobile_conf }}"
  when: >
    item.key not in (
      'listenport',
      'table',
      'preup',
      'postup',
      'predown',
      'postdown'
      )

- name: "adding user configured mobile fields"
  set_fact:
    wireguard_mobile_conf: >
      {{
        wireguard_mobile_conf_clean |
        combine(wireguard_mobile_parameters[wireguard_interface] | default({}))
      }}

- name: setting file name
  set_fact:
    wireguard_template_dest: "{{ wireguard_mobile_conf_dir }}/{{ peername }}.{{ wireguard_interface }}.conf"

- name: "create {{ peername }} config"
  template:
    src: templates/etc/wireguard/wireguard_interface.conf.j2
    dest: "{{ wireguard_template_dest }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    - wireguard_conf: wireguard_mobile_conf
