---
# This task is looped on from tasks/main.yml and the variable
# wireguard_interface represents the wireguard interface being configured
# (e.g. wg0, wg1).

- name: create config file
  template:
    src: templates/etc/wireguard/wireguard_interface.conf.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: 0600
  vars:
    - wireguard_conf: "{{ wireguard[wireguard_interface] | auto_assign_ips | remove_self }}"

- name: enable wg-quick
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes

- name: configure unbound records
  include_tasks: configure_unbound_records.yml
  when: wireguard_conf.unbound_records|default(false)
  vars:
    - wireguard_conf: "{{ wireguard[wireguard_interface] | auto_assign_ips | remove_self }}"
