---

- name: "Create wireguard mobile directory if necessary"
  file:
    path: "{{ wireguard_mobile_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: setting file name
  set_fact:
    wireguard_template_dest: "{{ wireguard_mobile_conf_dir }}/{{ peername }}.{{ wireguard_interface }}.conf"

- name: "create {{ peername }} config"
  template:
    src: templates/etc/wireguard/wireguard_interface.conf.j2
    dest: "{{ wireguard_template_dest }}"
    owner: root
    group: root
    mode: '0644'
  vars:
    - wireguard_conf: >
        wireguard[wireguard_interface]                       |
        combine({
          'privkey':
            wireguard[wireguard_interface].
              peers[peername].
              privkey | default('<your private key here>')
          })                                                 |
        auto_assign_ips                                      |
        remove_self                                          |
        keep_keys(
          [
            'listenport',
            'table',
            'preup',
            'postup',
            'predown',
            'postdown'
          ])                                                 |
        combine(
          wireguard_mobile_parameters[wireguard_interface] |
          default({})
        )
