---

- name: accept wireguard connections
  iptables:
    comment: "{{ wireguard_interface }}_protocol"
    chain: INPUT
    protocol: udp
    destination_port: "{{ wireguard_conf.listenport }}"
    ctstate: NEW
    jump: ACCEPT
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  when: ('listenport' in wireguard_conf)

- name: allow forwarding of packets that stay in the tunnel
  iptables:
    comment: "{{ wireguard_interface }}_to_{{ wireguard_interface }}"
    chain: FORWARD
    in_interface: "{{ wireguard_interface }}"
    out_interface: "{{ wireguard_interface }}"
    ctstate: NEW
    jump: ACCEPT
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  when: ('out_gw' in wireguard_conf)

- name: allow forwarding of packets from peers to the Internet
  iptables:
    comment: "{{ wireguard_interface }}_to_{{ wireguard_conf.out_gw }}"
    chain: FORWARD
    in_interface: "{{ wireguard_interface }}"
    out_interface: "{{ wireguard_conf.out_gw }}"
    ctstate: NEW
    jump: ACCEPT
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  when: ('out_gw' in wireguard_conf)

- name: masquerade v4 packets to the out interface
  iptables:
    comment: "{{ wireguard_interface }}_masquerade"
    table: nat
    chain: POSTROUTING
    out_interface: "{{ wireguard_conf.out_gw }}"
    jump: MASQUERADE
    ip_version: ipv4
  when: ('out_gw' in wireguard_conf)

- name: allow wifi traffic to be forwarded to wireguard
  iptables:
    comment: "{{ wireguard_interface }}_wifi_to_vpn"
    chain: FORWARD
    in_interface: "{{ wireguard_conf.in_gw }}"
    out_interface: "{{ wireguard_interface }}"
    ctstate: NEW
    jump: ACCEPT
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  when: ('in_gw' in wireguard_conf)

- name: masquerade v4 packets to wireguard
  iptables:
    comment: "{{ wireguard_interface }}_masquerade_wifi"
    table: nat
    chain: POSTROUTING
    out_interface: "{{ wireguard_interface }}"
    jump: MASQUERADE
    ip_version: ipv4
  when: ('in_gw' in wireguard_conf)
