---
- name: Install the packages required for building wireguard
  package: name={{ item }} state=latest
  with_items:
    - raspberrypi-kernel-headers
    - dirmngr

- name: update apt pin preferences
  copy:
    src: files/etc/apt/preferences.d/limit-unstable
    dest: /etc/apt/preferences.d/limit-unstable
    owner: root
    group: root
    mode: 0644

- name: Add the debian signing keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 648ACFD622F3D138
    - 04EE7237B7D453EC

- name: add unstable repo
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    filename: unstable-wireguard
    state: present

- name: get latest wireguard
  package: name=wireguard state=latest

- name: load wireguard kernel module automatically at boot
  copy:
    dest: /etc/modules-load.d/wireguard.conf
    content: |
      # ansible managed
      wireguard
