---
- name: Enable wireguard COPR repository
  get_url:
    dest: /etc/yum.repos.d/_copr_jdoss-wireguard.repo
    url: "https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/epel-{{ ansible_distribution_major_version }}/jdoss-wireguard-epel-{{ ansible_distribution_major_version }}.repo"

- name: Enable EPEL
  package:
    name: epel-release
    state: present

- name: Install wireguard
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wireguard-dkms
    - wireguard-tools
