---
- name: install wireguard
  include_tasks: "{{ install_wireguard }}"
  with_first_found:
    - "install_{{ ansible_distribution }}_{{ ansible_machine }}.yml"
    - "install_{{ ansible_os_family }}_{{ ansible_machine }}.yml"
    - install_default.yml
  loop_control:
    loop_var: install_wireguard

- name: configure networks
  include_tasks: configure_wireguard_interface.yml
  with_items: "{{ wireguard.keys()|list|sort }}"
  loop_control:
    loop_var: wireguard_interface
